apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: maven-build
spec:
  workspaces:
  - name: local-maven-repo
  - name: local-dockerfile
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image  
  tasks:
  - name: build
    taskRef:
      name: maven
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: destination
        resource: app-image
    params:
    - name: GOALS
      value: ["clean","package"]
    - name: DOCKERFILE
      value: "Dockerfile"  
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: dockerfile
      workspace: local-dockerfile